// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIuKt-dVaq2EZIoN5kpORiMtCYUahr3Tw',
    appId: '1:451837752323:web:8acd848728fd2d8f5f0a36',
    messagingSenderId: '451837752323',
    projectId: 'pawmate-7e881',
    authDomain: 'pawmate-7e881.firebaseapp.com',
    storageBucket: 'pawmate-7e881.firebasestorage.app',
    measurementId: 'G-V0HQ2M96XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6cjm9UdXcbB88i8D5HP8MEiP8QF8V8rc',
    appId: '1:451837752323:android:551bfa9e5b969bbc5f0a36',
    messagingSenderId: '451837752323',
    projectId: 'pawmate-7e881',
    storageBucket: 'pawmate-7e881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsa-xRuC-B_bqNvP3Eo_sKx9Zz_opVGJQ',
    appId: '1:451837752323:ios:7d413ad98c5266c55f0a36',
    messagingSenderId: '451837752323',
    projectId: 'pawmate-7e881',
    storageBucket: 'pawmate-7e881.firebasestorage.app',
    iosBundleId: 'com.seizeh.pawmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsa-xRuC-B_bqNvP3Eo_sKx9Zz_opVGJQ',
    appId: '1:451837752323:ios:7d413ad98c5266c55f0a36',
    messagingSenderId: '451837752323',
    projectId: 'pawmate-7e881',
    storageBucket: 'pawmate-7e881.firebasestorage.app',
    iosBundleId: 'com.seizeh.pawmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIuKt-dVaq2EZIoN5kpORiMtCYUahr3Tw',
    appId: '1:451837752323:web:9aef34d86d0a24665f0a36',
    messagingSenderId: '451837752323',
    projectId: 'pawmate-7e881',
    authDomain: 'pawmate-7e881.firebaseapp.com',
    storageBucket: 'pawmate-7e881.firebasestorage.app',
    measurementId: 'G-QYXKCNRQXW',
  );
}
